# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thinbass.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Thinbass(object):
    def setupUi(self, Thinbass):
        Thinbass.setObjectName("Thinbass")
        Thinbass.setWindowModality(QtCore.Qt.ApplicationModal)
        Thinbass.resize(412, 240)
        self.gridLayout = QtWidgets.QGridLayout(Thinbass)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(Thinbass)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.settings_button = QtWidgets.QPushButton(Thinbass)
        self.settings_button.setObjectName("settings_button")
        self.horizontalLayout_4.addWidget(self.settings_button)
        self.output_button = QtWidgets.QPushButton(Thinbass)
        self.output_button.setObjectName("output_button")
        self.horizontalLayout_4.addWidget(self.output_button)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.cancel_button = QtWidgets.QPushButton(Thinbass)
        self.cancel_button.setObjectName("cancel_button")
        self.horizontalLayout_4.addWidget(self.cancel_button)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 10)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.setStretch(3, 1)
        self.verticalLayout_2.setStretch(4, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Thinbass)
        self.cancel_button.clicked.connect(Thinbass.close)
        self.output_button.clicked.connect(Thinbass.close)
        self.settings_button.clicked.connect(Thinbass.close)
        self.output_button.clicked.connect(Thinbass.output)
        self.settings_button.clicked.connect(Thinbass.settings)
        QtCore.QMetaObject.connectSlotsByName(Thinbass)

    def retranslateUi(self, Thinbass):
        _translate = QtCore.QCoreApplication.translate
        Thinbass.setWindowTitle(_translate("Thinbass", "Dialog"))
        self.label_2.setText(_translate("Thinbass", "Multiple sources for constructing the list of variables have been detected. \n"
"Please choose one of the following sources:"))
        self.settings_button.setText(_translate("Thinbass", "Settings files"))
        self.output_button.setText(_translate("Thinbass", "BASSPRO output"))
        self.cancel_button.setText(_translate("Thinbass", "Cancel"))
