# DESCRIPTION:
# tibblemaker.r reads in all json files generated by Breathcaller for any given run of PAPR. 
# It also performs some manipulations to prepare the data for the pipeline.
print("Importing data")


#########################
#####JSON LOCATION#######
#########################
#Sets working directory to the Mothership so arguments in command line that indicate file locations are 
#understood and found by R.
# setwd("~/") 
setwd(args$dir)

#Imports all JSON files in file location indicated in args$JSON.
full_dirs <- unlist(strsplit(args$JSON, ","))
filepaths <- list.files(full_dirs, pattern = "\\.json", full.names = TRUE, recursive = TRUE)

#########################
#####IMPORT JSONS########
#########################
#Function that imports all JSON files in the indicated folder and appends them into one tibble. 
import_data <- function(fp){
  #Function to convert NULL and "" values in the raw json to NA (necessitated by R handling of NULL values)
  blank_to_na <- function(xx){
    new_xx <- unlist(lapply(xx, function(x) ifelse(((x == "")|(is.na(x))|(x == "NA")), NA, x)))
    return(new_xx)
  }
  
  null_to_na <- function(xx){
    new_xx <- unlist(lapply(xx, function(x) ifelse(is.null(x), NA, x)))
    return(new_xx)
  }
  
  #For each mouse, import and attach to overall tbl.
  for(ii in fp){
    if(grepl("config", ii)) {next}
    print(paste0("Adding file:", ii))
    
    #Raw import
    temp_json <- rjson::fromJSON(file = ii, simplify = FALSE)
    
    #Convert NULL to NA
    temp_list <- lapply(temp_json, null_to_na)
    temp_list <- lapply(temp_list, blank_to_na)
    
    # Turn json to tbl
    temp_df <- as_tibble(temp_list)
    
    if(!exists("breath_df")){
      # Create breath_df
      breath_df <- temp_df 
    } else {
      # Check if types match
      for(col_num in 1:ncol(breath_df)){
        col_name <- colnames(breath_df)[col_num]
        if((!is.null(temp_df[[col_name]])) & (class(breath_df[[col_name]]) != class(temp_df[[col_name]]))) {
          breath_df[[col_name]] <- as.character(breath_df[[col_name]])
          temp_df[[col_name]] <- as.character(temp_df[[col_name]])
        }
      }
      # Attach to overall tbl.
      breath_df <- bind_rows(breath_df, temp_df)
    }
    
  }
  
  # Check if character column should be numeric
  for(col_num in 1:ncol(breath_df)){
    suppressWarnings(temp_comp <- as.numeric(breath_df[[col_num]]))
    if(sum(is.na(breath_df[[col_num]])) == sum(is.na(temp_comp))) {
      breath_df[[col_num]] <- temp_comp
    }
  }
  
  return(breath_df)
} 

#Performs the above function and loads in all JSON files as one tibble.
tbl0 <- import_data(filepaths)

# Converts column names to names without units.
wu_convert <- function(colname) {
  if(is.na(colname)){
    return("")
  } else if((length(colname) == 0) || (colname == "")){
    return(colname)
  } else {
    return(c(strsplit(colname, "\\(")[[1]][1] %>%
             str_replace_all(" ", "")))
  }
}

#########################
#### R CONFIGURATION ####
#########################

print("Loading variable configuration")

#Loads R configuration file. This file has settings for independent, dependent, and covariate variables;
#body weight and temperature; and alias assignment if a variable name change is desired by the user.
var_names <- read.csv(args$R_config, stringsAsFactors=FALSE, na.strings = c("NA", "", " "))
# var_names <- read.csv("/D/Resp/papr_6_20/papr_7_4/R_config/r_config3.csv", stringsAsFactors=FALSE)

#Convert to names without units.
var_names$With_units <- var_names$Alias
var_names$Alias <- sapply(var_names$With_units, wu_convert)


#Sets columns names to designated alias names. These aliases are set by the user in the GUI. 
setnames(tbl0, old = c(var_names$Column), new = c(var_names$Alias), skip_absent = TRUE)

#Sets statistical values for dependent, independent, and covariate varibales based on R_config file.
response_vars <- var_names$Alias[which(var_names$Dependent != 0)]
covariates <- var_names$Alias[which(var_names$Covariate != 0)]
interaction_vars <- var_names$Alias[which(var_names$Independent != 0)]

#Custom graph ranges
ymins <- as.numeric(var_names$ymin[which(var_names$Dependent != 0)])
ymaxes <- as.numeric(var_names$ymax[which(var_names$Dependent != 0)])

# Correct for user settings
for(jj in interaction_vars){
  if(typeof(tbl0[[jj]]) == "numeric"){
    tbl0[[jj]] <- as.character(tbl0[[jj]])
  }
  if(length(unique(tbl0[[jj]])) == 1){
   warning(paste0("Independent variable ", jj, " has only one unique value. Results may be unreliable."))
 }
  if(length(unique(tbl0[[jj]])) > 20){
    warning(paste0("Independent variable ", jj, " has many unique values; this may cause memory issues. Should this be a covariate?"))
  }
}

for(jj in covariates){
  if(length(unique(tbl0[[jj]])) == 1){
    warning(paste0("Covariate ", jj, " has only one unique value. Results may be unreliable."))
  }
}

#Determines if extra graphs are plotted per user choices.
spec_vars <- var_names$Alias[which(var_names$Spectral != 0)]
poincare_vars <- var_names$Alias[which(var_names$Poincare != 0)]
transform_set <- var_names$Transformation[which(var_names$Dependent != 0)]
  
#########################
##### GRAPH CONFIG ######
#########################


#Load Graph configuration file.
print("Loading graph settings")
graph_vars <- read.csv(args$Graph, stringsAsFactors = FALSE)
# graph_vars <- read.csv("/D/Resp/Mothership_5-20-2021/G_config/graph_config4.csv")
graph_vars$Alias <- as.character(graph_vars$Alias)
graph_vars$Role <- as.numeric(graph_vars$Role)

#Convert to names without units.
graph_vars$With_units <- as.character(graph_vars$Alias)
graph_vars$Alias <- sapply(graph_vars$With_units, wu_convert)

#Sets statistical values for dependent, independent, and covariate variables based on R_config file.
xvar_wu <- graph_vars$With_units[which(graph_vars$Role == 1)]
pointdodge_wu <- graph_vars$With_units[which(graph_vars$Role == 2)]
facet1_wu <- graph_vars$With_units[which(graph_vars$Role == 3)]
facet2_wu <- graph_vars$With_units[which(graph_vars$Role == 4)]

xvar <- graph_vars$Alias[which(graph_vars$Role == 1)]
pointdodge <- graph_vars$Alias[which(graph_vars$Role == 2)]
facet1 <- graph_vars$Alias[which(graph_vars$Role == 3)]
facet2 <- graph_vars$Alias[which(graph_vars$Role == 4)]


# Checks that graphing variables are categorical
for(gg in c(xvar, pointdodge, facet1, facet2)){
  if(length(unique(tbl0[[gg]])) > 8) {
    warning(paste0("Graphing variable ", gg, " has more than 8 categories; your graphs may become illegible. Is this a numeric variable?"))}
}

#########################
### USER GRAPH CONFIG ###
#########################

print("Loading optional graph settings")

other_config <- read.csv(args$Foxtrot, stringsAsFactors = FALSE, na.strings = c("", " ", "NA"))
if(is.null(args$I)){
  args$I <- ".svg"
}

##########################
## Character Conversion ##
##########################

for(ii in 1:ncol(tbl0)){
  if(typeof(tbl0[[ii]]) == "character"){
    tbl0[[ii]] <- str_trunc(tbl0[[ii]], 25, side = "center", ellipsis = "___")
  }
}


# Savepoint
save.image(file = paste0(args$Output, "/", format(Sys.time(), "%m%d%y_%H%M%S"), ".RData"))

